on:
  push:
    branches:
      - main

name: Test action

jobs:
  start-runner:
    name: Start runner test for action
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ vars.AWS_RUNNER_REGION }}
          role-to-assume: ${{ vars.AWS_RUNNER_ROLE }}
      - name: Start EC2 instance
        uses: ./
        with:
          mode: start
          ec2-image-id: ${{ vars.AWS_RUNNER_AMI_ID }}
          ec2-instance-type: 't3.micro'
          ec2-reuse-instance: 'true'
          ec2-region: ${{ vars.AWS_RUNNER_REGION }}
          subnet-id: ${{ vars.AWS_RUNNER_SUBNET_ID }}
          security-group-id: ${{ vars.AWS_RUNNER_SECURITY_GROUP_ID }}
          aws-resource-tags: '[{"Key": "Runner", "Value": "1"}]'
          runner-home-dir: '/home/ubuntu/actions-runner'
          auto-termination: 'true'
          termination-delay: '10'
          github-token: ${{ secrets.AWS_RUNNER_GITHUB_TOKEN }}
          github-runner-group: 'default'
  do-the-job:
    name: Do the job on the runner
    needs: start-runner # required to start the main job when the runner is ready
    runs-on:
      group: ${{ needs.start-runner.outputs.runner-group }}
    steps:
      - name: Hello World
        run: echo 'Hello World!'
